geekshop/authapp/urls.py
from django.urls import path, re_path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('user/register/', authapp.register, name='register'),
    path('user/edit/', authapp.edit, name='edit'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
]

geekshop/geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('new/admin/', include('adminapp.urls', namespace='new_admin')),
    path('social/', include('social_django.urls', namespace='social')),
    path('order/', include('ordersapp.urls', namespace='order')),

    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/mainapp/urls.py
from django.urls import path, re_path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.Index.as_view(), name='index'),
    path('new/', mainapp.Index.as_view(), name='index_new'),
    path('products/', mainapp.Products.as_view(), name='products'),
    path('contact/', mainapp.Contact.as_view(), name='contact'),
    path('category/<int:pk>/', mainapp.Category.as_view(), name='category'),
    path('product/<int:pk>/', mainapp.ProductPage.as_view(), name='product_page'),
    path('product/<int:pk>/price/', mainapp.get_product_price),
]

geekshop/ordersapp/urls.py
import ordersapp.views as ordersapp
from django.urls import path


app_name = 'ordersapp'


urlpatterns = [
    path('', ordersapp.OrderList.as_view(), name='orders_list'),
    path('forming/complete/<int:pk>/', ordersapp.order_forming_complete, name='order_forming_complete'),
    path('create/', ordersapp.OrderItemsCreate.as_view(), name='order_create'),
    path('read/<int:pk>/', ordersapp.OrderRead.as_view(), name='order_read'),
    path('update/<int:pk>/', ordersapp.OrderItemsUpdate.as_view(), name='order_update'),
    path('delete/<int:pk>', ordersapp.OrderDelete.as_view(), name='order_delete')
]

geekshop/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField('имя', max_length=64)
    description = models.TextField('описание', blank=True)
    short_desc = models.CharField('краткое описание', max_length=200, blank=True)
    is_active = models.BooleanField('активность', default=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'категория продукта'
        verbose_name_plural = 'категории продукта'
        ordering = ['name']

    def delete(self, using=None, keep_parents=False):
        self.is_active = False
        self.save(using=using)


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField('имя', max_length=64)
    image = models.ImageField(upload_to='products_images', blank=True)
    description = models.TextField('описание', blank=True)
    short_desc = models.CharField('краткое описание', max_length=200, blank=True)
    price = models.DecimalField('цена', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField('количество на складе', default=0)
    created = models.DateTimeField(verbose_name='создан', auto_now_add=True)
    views = models.IntegerField('просмотры', default=0)
    is_active = models.BooleanField('активность', default=True)

    def __str__(self):
        return f'{self.name} ({self.category.name})'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        ordering = ['name']

geekshop/mainapp/views.py
import random
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404
from mainapp.models import Product, ProductCategory
from django.views.generic import View


def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'


def get_product_price(request, pk):
    if is_ajax(request=request):
        product = Product.objects.filter(pk=pk).first()
        return JsonResponse(
            {'price': product and product.price or 0}
        )


def get_hot_product():
    product_ids = Product.objects.values_list('id', flat=True).all()
    random_id = random.choice(product_ids)
    return Product.objects.get(pk=random_id)


def get_popular_products():
    return Product.objects.all().order_by('-views')[:4]


def get_new_products():
    return Product.objects.all().order_by('-created')[:4]


def same_products(hot_product):
    return Product.objects.filter(category=hot_product.category). \
               exclude(pk=hot_product.pk)[:3]


class Index(View):
    def get(self, request):
        context = {'page_title': 'главная',
                   'top_products': get_popular_products(),
                   'new_products': get_new_products(), }
        return render(request, 'mainapp/index.html', context)


class Products(View):
    def get(self, request):
        hot_product = get_hot_product()
        context = {'page_title': 'каталог',
                   'hot_product': hot_product,
                   'same_products': same_products(hot_product), }
        return render(request, 'mainapp/products.html', context)


class Category(View):
    def get(self, request, pk):
        page_num = request.GET.get('page', 1)
        if pk == 0:
            category = {'pk': 0, 'name': 'все'}
            products = Product.objects.all()
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = category.product_set.all()

        products_paginator = Paginator(products, 2)
        try:
            products = products_paginator.page(page_num)
        except PageNotAnInteger:
            products = products_paginator.page(1)
        except EmptyPage:
            products = products_paginator.page(products_paginator.num_pages)

        context = {
            'page_title': 'товары категории',
            'category': category,
            'products': products,
        }
        return render(request, 'mainapp/category_products.html', context)


class ProductPage(View):
    def get(self, request, pk):
        product = get_object_or_404(Product, pk=pk)
        product.views += 1
        product.save()
        context = {
            'page_title': 'страница продукта',
            'product': product,
        }
        return render(request, 'mainapp/product_page.html', context)


class Contact(View):
    def get(self, request):
        locations = [
            {'city': 'Москва',
             'phone': '+7-888-444-7777',
             'email': 'info@geekshop.ru',
             'address': 'В пределах МКАД'},
            {'city': 'Санкт-Петербург',
             'phone': '+7-888-333-9999',
             'email': 'info.spb@geekshop.ru',
             'address': 'В пределах КАД'},
            {'city': 'Хабаровск',
             'phone': '+7-888-222-3333',
             'email': 'info.east@geekshop.ru',
             'address': 'В пределах центра'},
        ]

        context = {
            'page_title': 'контакты',
            'locations': locations,
        }
        return render(request, 'mainapp/contact.html', context)

geekshop/mainapp/templates/mainapp/includes/catalog_menu.html
<div class="links clearfix">
    <ul class="links-menu">
        <li>
            <a href="{% url 'main:category' 0 %}"
               class="{% if request.resolver_match.url_name == 'category' and request.resolver_match.kwargs.pk == 0 %}active{% endif %}">
                все
            </a>
        </li>

        {% for item in categories %}
            <li>
                <a href="{% url 'main:category' item.pk %}"
                   class="{% if request.resolver_match.url_name == 'category' and request.resolver_match.kwargs.pk == item.pk %}active{% endif %}">
                    {{ item.name }}
                </a>
            </li>
        {% endfor %}
    </ul>
</div>

geekshop/mainapp/templates/mainapp/includes/main_menu.html
<div class="header clearfix">
    <a href="{% url 'main:index' %}" class="logo"></a>
    <ul class="menu">
        <li>
            <a href="{% url 'main:index' %}"
               class="{% if request.resolver_match.url_name == 'index' %}active{% endif %}">
                домой
            </a>
        </li>
        <li>
            <a href="{% url 'main:products' %}"
                class="{% if request.resolver_match.url_name == 'products' or request.resolver_match.url_name == 'category' %}active{% endif %}">
                продукты
            </a>
        </li>
        <li>
            <a href="{% url 'main:contact' %}"
                class="{% if request.resolver_match.url_name == 'contact' %}active{% endif %}">
                контакты
            </a>
        </li>
        {% if user.is_authenticated %}
            <li>
                <div class="dropdown">
                    <a class="dropdown-toggle" href="" data-toggle="dropdown">
                        {{ user.first_name|default:"пользователь"|capfirst }}
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="{% url 'auth:edit' %}">
                                профиль
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'order:orders_list' %}">
                                заказы
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
        {% endif %}
        {% if user.is_superuser %}
            <li>
                <a href="{% url 'new_admin:index' %}">
                    Админка
                </a>
            </li>
        {% endif %}
        <li>
            {% if user.is_authenticated %}
                <a href="{% url 'auth:logout' %}">
                    выйти
                </a>
            {% else %}
                <a href="{% url 'auth:login' %}">
                    войти
                </a>
            {% endif %}
        </li>
    </ul>
    <a href="#" class="search"></a>
    <a href="{% url 'basket:index' %}" class="basket">
        {% if user.is_authenticated %}
            <span>{{ user.basket_price|floatformat:0 }} руб ({{ user.basket_qty }} шт)</span>
        {% endif %}
    </a>
</div>