geekshop/authapp/urls.py
from django.urls import path, re_path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('user/register/', authapp.register, name='register'),
    path('user/edit/', authapp.edit, name='edit'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
]

geekshop/basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.index, name='index'),
    path('add/<int:product_pk>/', basketapp.add, name='add'),
    path('remove/<int:basket_item_pk>/', basketapp.remove, name='remove'),
    # "/basket/update/" + basketItemPk + "/" + qty + "/"
    path('update/<int:basket_item_pk>/<int:qty>/', basketapp.update),
]

geekshop/geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('new/admin/', include('adminapp.urls', namespace='new_admin')),
    path('social/', include('social_django.urls', namespace='social')),
    path('order/', include('ordersapp.urls', namespace='order')),

    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/mainapp/urls.py
from django.urls import path, re_path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.Index.as_view(), name='index'),
    path('new/', mainapp.Index.as_view(), name='index_new'),
    path('products/', mainapp.Products.as_view(), name='products'),
    path('contact/', mainapp.Contact.as_view(), name='contact'),
    path('category/<int:pk>/', mainapp.Category.as_view(), name='category'),
    path('product/<int:pk>/', mainapp.ProductPage.as_view(), name='product_page'),
    path('product/<int:pk>/price/', mainapp.get_product_price),
]

geekshop/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField('имя', max_length=64)
    description = models.TextField('описание', blank=True)
    short_desc = models.CharField('краткое описание', max_length=200, blank=True)
    is_active = models.BooleanField('активность', default=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'категория продукта'
        verbose_name_plural = 'категории продукта'
        ordering = ['name']

    def delete(self, using=None, keep_parents=False):
        self.is_active = False
        self.save(using=using)


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField('имя', max_length=64)
    image = models.ImageField(upload_to='products_images', blank=True)
    description = models.TextField('описание', blank=True)
    short_desc = models.CharField('краткое описание', max_length=200, blank=True)
    price = models.DecimalField('цена', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField('количество на складе', default=0)
    created = models.DateTimeField(verbose_name='создан', auto_now_add=True)
    views = models.IntegerField('просмотры', default=0)
    is_active = models.BooleanField('активность', default=True)

    def __str__(self):
        return f'{self.name} ({self.category.name})'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        ordering = ['name']

geekshop/mainapp/views.py
import random
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404
from mainapp.models import Product, ProductCategory
from django.views.generic import View


def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'


def get_product_price(request, pk):
    if is_ajax(request=request):
        product = Product.objects.filter(pk=pk).first()
        return JsonResponse(
            {'price': product and product.price or 0}
        )


def get_hot_product():
    product_ids = Product.objects.values_list('id', flat=True).all()
    random_id = random.choice(product_ids)
    return Product.objects.get(pk=random_id)


def get_popular_products():
    return Product.objects.all().order_by('-views')[:4]


def get_new_products():
    return Product.objects.all().order_by('-created')[:4]


def same_products(hot_product):
    return Product.objects.filter(category=hot_product.category). \
               exclude(pk=hot_product.pk)[:3]


class Index(View):
    def get(self, request):
        context = {'page_title': 'главная',
                   'top_products': get_popular_products(),
                   'new_products': get_new_products(), }
        return render(request, 'mainapp/index.html', context)


class Products(View):
    def get(self, request):
        hot_product = get_hot_product()
        context = {'page_title': 'каталог',
                   'hot_product': hot_product,
                   'same_products': same_products(hot_product), }
        return render(request, 'mainapp/products.html', context)


class Category(View):
    def get(self, request, pk):
        page_num = request.GET.get('page', 1)
        if pk == 0:
            category = {'pk': 0, 'name': 'все'}
            products = Product.objects.all()
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = category.product_set.all()

        products_paginator = Paginator(products, 2)
        try:
            products = products_paginator.page(page_num)
        except PageNotAnInteger:
            products = products_paginator.page(1)
        except EmptyPage:
            products = products_paginator.page(products_paginator.num_pages)

        context = {
            'page_title': 'товары категории',
            'category': category,
            'products': products,
        }
        return render(request, 'mainapp/category_products.html', context)


class ProductPage(View):
    def get(self, request, pk):
        product = get_object_or_404(Product, pk=pk)
        product.views += 1
        product.save()
        context = {
            'page_title': 'страница продукта',
            'product': product,
        }
        return render(request, 'mainapp/product_page.html', context)


class Contact(View):
    def get(self, request):
        locations = [
            {'city': 'Москва',
             'phone': '+7-888-444-7777',
             'email': 'info@geekshop.ru',
             'address': 'В пределах МКАД'},
            {'city': 'Санкт-Петербург',
             'phone': '+7-888-333-9999',
             'email': 'info.spb@geekshop.ru',
             'address': 'В пределах КАД'},
            {'city': 'Хабаровск',
             'phone': '+7-888-222-3333',
             'email': 'info.east@geekshop.ru',
             'address': 'В пределах центра'},
        ]

        context = {
            'page_title': 'контакты',
            'locations': locations,
        }
        return render(request, 'mainapp/contact.html', context)

geekshop/mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <title>
        {{ page_title|default:"магазин"|capfirst }}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% endblock %}
</head>
<body>
<div class="container">
    {% block container %}
    {% endblock %}

    <div class="clr"></div>

</div>

<div class="footer">
    <div class="clearfix">
        <div class="text-footer">
            <h3>контакты</h3>
        </div>
        <div class="text-footer">
            <h3>полезная информация</h3>
        </div>
        <div class="text-footer clearfix">
            <h3>Оставайтесь на связи</h3>
            <p>Подписаться на новости и рассылки</p>
            <form>
                <input type="email" name="email" placeholder="ваш email">
                <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
            </form>
        </div>
    </div>
    <p class="small">&copy; GB 2017</p>
    <div class="social">
        <a href="#" class="social1"></a>
        <a href="#" class="social2"></a>
        <a href="#" class="social3"></a>
        <a href="#" class="social4"></a>
    </div>
    <p class="small">Положения &amp; Условия / Конфиденциальность &amp; Cookies</p>
</div>

</body>
</html>

geekshop/mainapp/templates/mainapp/category_products.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block container %}
    <div class="hero-white">
        {% include 'mainapp/includes/main_menu.html' %}
    </div>

    <div class="details">
        {% include 'mainapp/includes/catalog_menu.html' %}

        <div class="related">
            <div class="title clearfix">
                <h2>Продукты категории {{ category.name|upper }}</h2>
            </div>
            <div class="paginator">
                {% if products.has_previous %}
                    <a href="{% url 'main:category' category.pk %}?page={{ products.previous_page_number }}">
                        <
                    </a>
                {% endif %}
                <span class="current">страница {{ products.number }} из {{ products.paginator.num_pages }}</span>
                {% if products.has_next %}
                    <a href="{% url 'main:category' category.pk %}?page={{ products.next_page_number }}">
                        >
                    </a>
                {% endif %}
            </div><br>
            <div class="related-products clearfix">
                {% for item in products %}
                    <div class="block">
                        <a href="{% url 'main:product_page' item.pk %}">
                            <img src="/media/{{ item.image }}" alt="">
                            <div class="text">
                                <img src="/static/img/icon-hover.png" alt="img">
                                <h4>{{ item.name }}</h4>
                                <p>{{ item.short_desc }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

geekshop/mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}

{% block container %}
    <div class="hero">
        {% include 'mainapp/includes/main_menu.html' %}
        <h1>наши контакты</h1>
    </div>
{#    <h3>{{ locations.0 }}</h3>#}
    <div class="location">
        {% for location_item in locations %}
            <div class="location-1 city city-{{ forloop.counter0 }}">
                <i class="fa fa-map-marker fa-5x"></i>
                <h4>{{ location_item.city }}</h4>
                <div class="contacts {{ forloop.counter0 }}">
                    <h5>Телефон</h5>
                    <p>{{ location_item.phone }}</p>
                </div>
                <div class="contacts {{ forloop.counter0 }}">
                    <h5>Email</h5>
                    <p>{{ location_item.email }}</p>
                </div>
                <div class="contacts {{ forloop.counter0 }}">
                    <h5>Адрес</h5>
                    <p>{{ location_item.address }}</p>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

geekshop/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}

{#{% block css %}#}
{#    <link rel="stylesheet" type="text/css" href="/static/css/main.css">#}
{#    {{ block.super }}#}
{#{% endblock %}#}


{% block container %}
    <div class="slider">
        {% include 'mainapp/includes/main_menu.html' %}
        <div class="text-slider">
            <h3 class="green">тенденции</h3>
            <h3 class="big"> удобные стулья</h3>
            <p>Новый уровень комфорта. Отличные характеристики.</p>
            <a href="{% url 'basket:add' 12 %}" class="button-order">заказать <img src="img/arrow.png" alt=""></a>
        </div>
        <div class="navi">
            <a href="#"></a><a href="#"></a><a href="#"></a>
        </div>
    </div>

    <div class="featured">
        <div class="featured-menu">
            <a class="{% if request.resolver_match.url_name == 'index' %}active{% endif %}" href="{% url 'main:index' %}">Популярные</a><a class="{% if request.resolver_match.url_name == 'index_new' %}active{% endif %}" href="{% url 'main:index_new' %}">Новинки</a>
        </div>
        <a class="explore" href="{% url 'main:category' 0 %}">показать все <img src="img/arrow.png" alt=""></a>
        <div class="clearfix">
        </div>
        <div class="tab-content">
            <div class="block">
                <a href="#"><img src="img/product-1.jpg" alt="">
                    <div class="text">
                        <img src="img/icon-hover.png" alt="img">
                        <h4>Отличный стул</h4>
                        <p>Расположитесь комфортно. </p>
                    </div>
                </a>
            </div>
            <div class="block">
                <a href="#"><img src="img/product-2.jpg" alt="">
                    <div class="text">
                        <img src="img/icon-hover.png" alt="">
                        <h4>Стул повышенного качества</h4>
                        <p>Не оторваться. </p>
                    </div>
                </a>
            </div>
            {% if request.resolver_match.url_name == 'index' %}
                {% for item in top_products %}
                    <div class="block">
                        <a href="{% url 'main:product_page' item.pk %}">
                            <img width="270" height="270" src="/media/{{ item.image }}" alt="">
                            <div class="text">
                                <img src="/static/img/icon-hover.png" alt="img">
                                <h4>{{ item.name }}</h4>
                                <p>{{ item.short_desc }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            {% else %}
                {% for item in new_products %}
                    <div class="block">
                        <a href="{% url 'main:product_page' item.pk %}">
                            <img width="270" height="270" src="/media/{{ item.image }}" alt="">
                            <div class="text">
                                <img src="/static/img/icon-hover.png" alt="img">
                                <h4>{{ item.name }}</h4>
                                <p>{{ item.short_desc }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
{% endblock %}

geekshop/mainapp/templates/mainapp/product_page.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block container %}
    <div class="hero-white">
        {% include 'mainapp/includes/main_menu.html' %}
    </div>

    <div class="details">
        {% include 'mainapp/includes/catalog_menu.html' %}

        <div class="details-products">
            <div class="details-slider">
                <div class="slider-product">
                    <img src="/media/{{ product.image }}" alt="slider prod">
                </div>
                <div class="slider-control">
                    <div class="block">
                        <a href="#"><img src="/media/{{ product.image }}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="/media/{{ product.image }}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="/media/{{ product.image }}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                </div>
            </div>

            <div class="description">
                <h3 class="big-bold">{{ product.name|capfirst }}</h3>
                <br>
                <p class="price"> {{ product.price }} <span>руб</span></p>
                <a href="{% url 'basket:add' product.pk %}" class="red-button">
                    заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
                </a>
                <div class="description-text">
                    <p>{{ product.short_desc }}</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

geekshop/mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block container %}
    <div class="hero-white">
        {% include 'mainapp/includes/main_menu.html' %}
    </div>

    <div class="details">
        {% include 'mainapp/includes/catalog_menu.html' %}

        <div class="details-products">
            <div class="details-slider">
                <div class="slider-product">
                    <img src="/media/{{ hot_product.image }}" alt="slider prod">
                </div>
                <div class="slider-control">
                    <div class="block">
                        <a href="#"><img src="/media/{{ hot_product.image }}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="/media/{{ hot_product.image }}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="/media/{{ hot_product.image }}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                </div>
            </div>

            <div class="description">
                <h3 class="big-bold">{{ hot_product.name|capfirst }}</h3>
                <h3 class="red">горячее предложение</h3>
                <p class="price"> {{ hot_product.price }} <span>руб</span></p>
                <a href="{% url 'basket:add' hot_product.pk %}" class="red-button">
                    заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
                </a>
                <div class="description-text">
                    <p>{{ hot_product.short_desc }}</p>
                </div>
            </div>
        </div>

        <div class="related">
            <div class="title clearfix">
                <h2>Похожие продукты</h2>
                <a class="explore" href="#">показать все <img src="/static/img/arrow.png" alt=""></a>
            </div>
            <div class="related-products clearfix">
                {% for item in same_products %}
                    <div class="block">
                        <a href="{% url 'main:product_page' item.pk %}">
                            <img src="/media/{{ item.image }}" alt="img">
                            <div class="text">
                                <img src="/static/img/icon-hover.png" alt="img">
                                <h4>{{ item.name }}</h4>
                                <p>{{ item.short_desc }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}